### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by jooyeon111** [Meinersbur/ppcg#4]
I was trying to compile this project. when i type make ,I got error message below.
**extract_interface.cc:34:10: fatal error: isl_config.h: No such file or directory
   34 | #include "isl_config.h"**
So, i tried with configure several "--with" command. but, it doesn't work.
Could you help me?

**Comment by Meinersbur** [comment]
The bundled pet requires clang with libraries to be installed on the system. The error is with the bundled isl for which clang is optional. The optional component (C/C++ bindings) can be disabled with `--with-clang=no`. Note that this is an option for isl's `configure` which you may need to build separately.

I just push up-to-date version to the repository which may already fix the whatever problem you have. But I am not maintaining ppcg/pet/isl. For questions, the isl-development@googlegroups.com / https://groups.google.com/g/isl-development mailing list would be the place to ask such questions.

**Comment by jooyeon111** [comment]
Thank you for answering. I have just solved the problem. Thanks!
